<a href="https://colab.research.google.com/github/Mariobahaa/Product-Recommendation-System-/blob/master/Product_Recommendation_System_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
modelName = 'digitalmusicalDrpbb' #Change Model Name !! IMPORTANT
maxLen = 1 #Do Not Change
path = '/content/drive/My Drive/Digital Music/Copy of Digital_Music_5.json.gz' #Data Path

In [ ]:
import pandas as pd
import gzip
import json
import numpy as np

# convert from json to pandas
def parse(path):
  g = gzip.open(path, 'rb')
  for l in g:
    yield json.loads(l)

def getDF(path):
  i = 0
  df = {}
  for d in parse(path):
    df[i] = d
    i += 1
  return pd.DataFrame.from_dict(df, orient='index')

# make dict and fit it by ids
def dict_ids(col):
  id = 1 # 1481  0
  dic = dict() 
  for i in col:
    if i in dic:
      dic[i] = dic.get(i)
    else:
      dic[i] = id
      id += 1
  return dic, (id-1)

# make new col by mapping last ids to new ids
def new_col(col,dic):
  lis = list()
  for i in col:
    #if i in dic:
    lis.append(dic.get(i))
  return lis

#create products per user map
def productsOfUser(userId, productId, ratings):
  productsOfUserMap = dict()
  ratesOfUserMap = dict()
  len_of_products = []

  for i in range(0,len(userId)):
    productsOfUserMap[userId[i]] = np.array([]).astype(int) #intm
    ratesOfUserMap[userId[i]] = np.array([]).astype(int) #intm

  for i in range(0,len(userId)): 
    if productId[i] > -1:
      productsOfUserMap[userId[i]] = np.append(productsOfUserMap[userId[i]] ,productId[i])
      ratesOfUserMap[userId[i]] = np.append(ratesOfUserMap[userId[i]] ,ratings[i])
  
  for i in productsOfUserMap.values():
    len_of_products.append((len(i)-1))
  len_of_products = np.array(len_of_products)
  return productsOfUserMap,len_of_products,ratesOfUserMap

def fixed_product_list(prodOfUser,len_of_products,numOfProds):
  # for i in range(0,len(len_of_products)):
  #   if max(len_of_products) != len_of_products[i]:
  #     zeroes= np.zeros(max(len_of_products) - len_of_products[i])
  #     prodOfUser[i] = np.append(prodOfUser[i],zeroes)
  zeroes = np.ones((len(len_of_products),max(len_of_products))) * numOfProds 
  for  i in range(0,len(prodOfUser)):
    temp = np.array(prodOfUser[i])
    zeroes[i,0:len(temp)] = temp
  return zeroes , max(len_of_products)

def duplicateUserBehaviour(X):
    newlist = []
    tests = []
    for item in X:
        userId = item[0]
        behaviour = item[1]
        rating = item[2]
        lastIndex = -1

        for i in range (0,len(behaviour)-1):
            itemList = []
            behaviourList = []
            itemList.append(userId)
            for j in range(0,i+1):
                behaviourList.append(behaviour[j])
                lastIndex = j
            candidate = behaviour[lastIndex+1]
            canrating = rating[lastIndex+1]
            if i == len(behaviour)-2:
                itemList.append(behaviourList)
                itemList.append(candidate)
                itemList.append(canrating)
                tests.append(itemList)
            else:
                itemList.append(behaviourList)
                itemList.append(candidate)
                itemList.append(canrating)
                newlist.append(itemList)
    return newlist, tests

In [ ]:
df_all_beauty = getDF(path)
# df_all_beauty = df_all_beauty[ df_all_beauty['overall']>0.1]

userId = np.array(df_all_beauty['reviewerID'])
dict_all_beauty_users, numUsers = dict_ids(userId)

productId = np.array(df_all_beauty['asin'])
dict_all_beauty_products, numProds = dict_ids(productId)


# ratings = np.array(df_all_beauty['overall'])
# dict_all_beauty_ratings = dict_ids(ratings)
# print (ratings)

userId =new_col(userId,dict_all_beauty_users)
productId =new_col(productId,dict_all_beauty_products)

#ratings = new_col(ratings, dict_all_beauty_ratings)

# categoryId = np.ones(len(productId)).astype(int)

# ratings = np.array(ratings).astype(float)
# norm_ratings = ratings/5.0
#  #(ratings - min(ratings)) /(max(ratings)-min(ratings))
# print(norm_ratings[0])

numOfProducts = len(dict_all_beauty_products)

#cateOfUser,len_of_category,ateOfUser = productsOfUser(userId, categoryId, norm_ratings)




# for i in len_of_products:
#   print (i)

# print(max(len_of_products))
# print(len(prodOfUser))




In [ ]:
#df_all_beauty = getDF(path)

ratings = np.array(df_all_beauty['overall'])
dict_all_beauty_ratings, maxRate = dict_ids(ratings)
z =0
o = 0
t = 0
th = 0
f = 0
fv = 0
for i in ratings:
    if i==0:
        z+=1
    if i==1:
        o+=1
    if i==2:
        t+=1
    if i==3:
        th+=1
    if i==4:
        f+=1
    if i==5:
        fv+=1
    
print(max(ratings))
print (min(ratings))
ratings = ratings/5.0
prodOfUser,len_of_products,rateOfUser = productsOfUser(userId, productId, ratings)
print (ratings)
numberOfUsers = 0
numberOfCategories = 0



for i in prodOfUser:
  numberOfUsers += 1

# for i in ratings:
#   if i == 5.0:
#     print(i)

5.0
1.0
[1. 1. 1. ... 1. 1. 1.]


In [ ]:
print(z)
print(o)
print(t)
print(th)
print(f)
print(fv)
print("all")
print(z+o+t+th) 
print(fv)

0
2192
1812
6792
23143
135842
all
10796
135842


In [ ]:
userId = np.empty([0,1]).astype(int)


for i in prodOfUser:
  userId = np.append(userId, i)

prodId =[None]*len(userId)
cateId =[None]*len(userId)
rates =[None]*len(userId)

for i in range(1,len(userId)+1): #1482 0 -> len 
  prod  = list(prodOfUser[i].reshape(len(prodOfUser[i]))) 
  prodId[i-1]= prod  #1483 i
  rate  = list(rateOfUser[i].reshape(len(rateOfUser[i])))
  rates[i-1]= rate   #1484 i
  # cate = list(cateOfUser[i].reshape(len(cateOfUser[i])))
  # cateId[i] = cate

candProd = np.array([]).astype(int)
candCate = np.array([]).astype(int)

# for i in range(0,len(userId)):
#   candProd = prodId[i-1]

maxLen = max(len_of_products)
#prodId, maxLen = fixed_product_list(prodId,len_of_products,numOfProducts)

In [ ]:
X = []
for i in range(0,len(userId)):
    X.append([userId[i],prodId[i],rates[i]])
newlist, tests = duplicateUserBehaviour(X)
print (tests[0])

[1, [1, 8240, 8965, 8967, 9074, 9222, 9398, 9547, 9550], 9568, 1.0]


In [ ]:
newlist = (np.array(newlist))
print(len(newlist[:,1]))
for i in range(0,len(newlist)):
  newlist[i][1] = np.array(newlist[i][1])

136651


In [ ]:
t_ones = fv
t_zeroes = z + o + t + th + f

def balance(p1,p2,nlist):
    if p1 > 0.6 *(p2 + p1):
        np.random.shuffle(nlist)
        p1 = p2 + (p2 * 0.2) #0.3
    if p2 > 0.6 * (p2+p1):
        np.random.shuffle(nlist)
        p1 = p1 + (p1 * 0.2) #0.3



    outlist = []
    for i in range(0,len(nlist)):
        if p1+p2 == 0:
            break
        
        if p1 > 0:
            if nlist[i][nlist.shape[-1]-1]> 0.8:
                p1 = p1 - 1
                outlist.append(np.array([nlist[i][0],nlist[i][1],nlist[i][2],nlist[i][3]]))
        if p2 > 0:
            if nlist[i][nlist.shape[-1]-1] <= 0.8:
                p2 = p2 - 1
                outlist.append(np.array([nlist[i][0],nlist[i][1],nlist[i][2],nlist[i][3]]))

    return np.array(outlist)


#newlist = balance(t_ones, t_zeroes, newlist)

In [ ]:
on = 0
for i in newlist:
    if i[3] > 0.8:
        on = on + 1

print(on/len(newlist))
        

0.7969425763441175


In [ ]:
print(len(newlist))
candRate=np.zeros((len(newlist),2)).astype(int)
print(len(candRate))
count_ones = 0
count_zeroes =0
for c in range(0,len(newlist)):
  if newlist[c][3] > 0.8:
    candRate[c][0] = 1.0
    count_ones +=1
  else:
    candRate[c][1] = 1.0
    count_zeroes +=1
candRate = np.array(candRate).astype(int)

candRate_test=np.zeros((len(tests),2)).astype(int)
for c in range(0,len(tests)):
  if tests[c][3] > 0.8:
    candRate_test[c][0] = 1.0
  else:
    candRate_test[c][1] = 1.0
candRate_test = np.array(candRate_test).astype(int)
# candRate1 = 1 - candRate

# candRate = candRate.reshape(candRate.shape[0],1)
# #candRate = np.array(candRate).astype(int)
# candRate1 = candRate1.reshape(candRate1.shape[0],1)
# #candRate = np.array(candRate).astype(int)
# candRate = np.append(candRate,candRate1,axis=1)
# candRate = np.array(candRate).astype(int)
# print(candRate)
print(count_ones)
print(count_zeroes)

136651
136651
108903
27748


In [ ]:

#Divides the X_train y_train or X_test y_test arrays to the arrays they are made of
def toOrigin(X):
    t_len = len(X)
    userId = np.zeros((t_len,1)).astype(int)
    prodId= np.zeros((t_len, maxLen)).astype(int) #Switch this 11 with a variable 
    candProd = np.zeros((t_len, 1)).astype(int) #Switch this 11 with a variable  
    candRate = np.zeros((t_len, 2)).astype(int)

    for i in range(0,t_len):
        userId[i,0] = X[i][0]
        # print (prodId.shape)
        # print (X[i][1].shape)
        prodId[i,0:len(X[i][1])] = X[i][1]
        candProd[i,0] = X[i][2]
        candRate[i,:] = X[i][3]
    return userId, prodId, candProd,candRate.astype(int)

In [ ]:
print(type(newlist[0]))

<class 'numpy.ndarray'>


In [ ]:
print(newlist.shape)

(136651, 4)


In [ ]:

userId_train, prodId_train, candProd_train, candRate_train = toOrigin(newlist)
userId_test, prodId_test, candProd_test, candrate_test = toOrigin(tests)
# print(userId_train.shape)
# #prodId_train = prodId_train.reshape(prodId_train.shape[0],1)
# print(np.array(prodId_train).shape)
# print(candProd_train)
# #userId_train = userId_train.reshape(userId_train.shape[0])
# print(userId_train.shape)
# candProd_train = candProd_train.reshape(candProd_train.shape[0])
# print(candProd_train.shape)
# print(type(prodId_train))
# print(userId_train.shape)
# print(prodId_train.shape)
# print(candProd_train.shape)
# for i in range(0,len(prodId_train)):
#   prodId_train[i] = np.array(prodId_train[i])
#   prodId_train[i] = np.expand_dims(prodId_train[i], axis=1)
# print(prodId_train[0].shape)

In [ ]:

print(userId_test.shape)
print(len(candRate_train))

(16564, 1)
136651


In [ ]:

print(prodId_train[0])
print(maxLen)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [ ]:
print(userId_train[0])
print(min(userId_train))
print(max(userId_train))
print(numUsers)

[1]
[1]
[16566]
16566


In [ ]:
print(candrate_test.shape)

(16564, 2)


In [ ]:
def Normalize(arr):
    mn = float(min(arr))
    mx = float(max(arr))
    arr = arr.astype(int)
    print(mn)
    print(mx)
    arr= (arr-mn)/(mx-mn)
    
    return arr, mn, mx

def vNormalize(arr, val):
    arr = arr.astype(int)
    val = float(val)
    arr = (arr-1.0)/(val-1.0)
    
    return arr,1,val

def vcNormalize(a, val):
    for arr in a:
        val = float(val)
        arr = (arr-1.0)/(val-1.0)
    
    return a,1,val



# userId_train, umin, umax = vNormalize(userId_train, numUsers)
# candProd_train, cmin, cmax= vNormalize(candProd_train,numProds)

# prodId_train, pmin, pmax= vcNormalize(prodId_train,numProds)



In [ ]:

# prodId_test = prodId_test[0]
# userId_test = userId_test[0]
# candProd_test= candProd_test[0]

In [ ]:

# userId_test = vNormalize(userId_test,numUsers)
# prodId_test = vcNormalize(prodId_test,numProds)
# candProd_test = vNormalize(candProd_test,numProds)



In [ ]:
vari = userId_train
print(vari)
print(max(vari))
print(min(vari))
print(type(vari[0][0]))

print(userId_train.shape)

[[    1]
 [    1]
 [    1]
 ...
 [16566]
 [16566]
 [16566]]
[16566]
[1]
<class 'numpy.int64'>
(136651, 1)


In [ ]:
userID_train = np.zeros((len(userId_train))).astype(int)
for i in range(0,len(userId_train)):
    userID_train[i] = userId_train[i][0]
print(userID_train)

[    1     1     1 ... 16566 16566 16566]


In [ ]:
vari = userId_test
print(vari)
print(max(vari))
print(min(vari))
print(type(vari[0][0]))

print(userId_train.shape)

[[    1]
 [    2]
 [    3]
 ...
 [16564]
 [16565]
 [16566]]
[16566]
[1]
<class 'numpy.int64'>
(136651, 1)


In [ ]:
userID_test = np.zeros((len(userId_test))).astype(int)
for i in range(0,len(userId_test)):
    userID_test[i] = userId_test[i][0]
print(userID_test)

[    1     2     3 ... 16564 16565 16566]


In [ ]:
vari = candProd_train
print(vari)
print(max(vari))
print(min(vari))
print(type(vari[0][0]))

print(vari.shape)

[[ 8240]
 [ 8965]
 [ 8967]
 ...
 [ 9283]
 [ 9384]
 [11780]]
[11794]
[1]
<class 'numpy.int64'>
(136651, 1)


In [ ]:
candprod_train = np.zeros((len(candProd_train))).astype(int)
for i in range(0,len(candProd_train)):
    candprod_train[i] = candProd_train[i][0]
print(candprod_train)

[ 8240  8965  8967 ...  9283  9384 11780]


In [ ]:
vari = candProd_test
print(vari)
print(max(vari))
print(min(vari))
print(type(vari[0][0]))

print(vari.shape)

[[ 9568]
 [ 4090]
 [ 8524]
 ...
 [11751]
 [11792]
 [11792]]
[11797]
[8]
<class 'numpy.int64'>
(16564, 1)


In [ ]:
candprod_test = np.zeros((len(candProd_test))).astype(int)
for i in range(0,len(candProd_test)):
    candprod_test[i] = candProd_test[i][0]
print(candprod_test)

[ 9568  4090  8524 ... 11751 11792 11792]


In [ ]:
print(userID_train.shape)
print(userID_test.shape)

print(prodId_train.shape)
print(prodId_test.shape)

print(candprod_train.shape)
print(candprod_test.shape)


(136651,)
(16564,)
(136651, 790)
(16564, 790)
(136651,)
(16564,)


In [ ]:
userId_train = userID_train
userId_test = userID_test

candProd_train = candprod_train
candProd_test = candprod_test

In [ ]:
print(max(userId_train))
print(numUsers)

16566
16566


In [ ]:
# Try to expand
userId_train = np.expand_dims(userId_train,axis=1)
candProd_train = np.expand_dims(candProd_train,axis=1)
print(userId_train.shape)
print(candProd_train)

(136651, 1)
[[ 8240]
 [ 8965]
 [ 8967]
 ...
 [ 9283]
 [ 9384]
 [11780]]


In [ ]:
from tensorflow.python.keras.models import Model
import numpy as np
from tensorflow.python.keras.models import Sequential, load_model
from tensorflow.python.keras.layers import  AveragePooling1D, Flatten, Dense, Dropout, Embedding, Lambda, Input, Concatenate, PReLU, BatchNormalization
from tensorflow.python.keras.callbacks import ModelCheckpoint
from tensorflow.python.keras.metrics import binary_accuracy , categorical_accuracy
from tensorflow.python.keras import regularizers
from tensorflow.python.keras.initializers import TruncatedNormal
import tensorflow as tf

embedOutDim = 400 #200,400,1000
attention_scale = 100 #1,10,100
poolSize = 2

#, embeddings_regularizer= regularizers.l2(0.01) 1485

##################################################################
userInput =  Input(shape=(1,), name= 'users')
#userInput =  tf.keras.layers.Masking(mask_value=0.0)(userInput)
userEmbed =  Embedding(input_dim =numberOfUsers+1,output_dim= embedOutDim, mask_zero =True) (userInput)


##################################################################
prodInput =  Input(shape=(maxLen,), name= 'products') #batch_shape(None, None)
#prodInputs =  tf.keras.layers.Masking(mask_value=0)(prodInput)
prodEmbed =  Embedding(input_dim =numProds,output_dim= embedOutDim, mask_zero =True ) (prodInput)
#print(prodInput.shape)

##################################################################
# cateInput = Input(shape=(11,), name= 'categories')
# cateEmbed =  Embedding(input_dim = numberOfCategories , output_dim=embedOutDim, embeddings_regularizer= regularizers.l2(0.01)) (cateInput)

##################################################################
candProdInput = Input(shape=(1,),  name= 'candidateProdId')
candProdEmbed =  Embedding(input_dim = numProds +1 , output_dim=embedOutDim, mask_zero =True) (candProdInput)

##################################################################
# candCateInput = Input(shape=(1,),  name= 'candidateCateId')
# candCateEmbed =  Embedding(input_dim = numberOfCategories , output_dim=embedOutDim, embeddings_regularizer= regularizers.l2(0.01)) (candCateInput)

#lenInput = Input(shape=(1,), name= 'len_of_products')

candProdEmbed = Dropout(0.5)(candProdEmbed)
prodEmbed = Dropout(0.5)(prodEmbed)
userEmbed = Dropout(0.5)(userEmbed)


#Goods  =Concatenate()([prodEmbed,cateEmbed]) #Uncomment for original work 
Goods = prodEmbed

#Goods  =  Lambda(lambda x: tf.keras.backend.batch_flatten(x))(Goods)
#print(Goods.shape)
# SeqPoolLayer = SequencePoolingLayer("sum",supports_masking= False)([Goods,lenInput]) #Error 

WeightedGoods = tf.keras.layers.Attention(use_scale= attention_scale)([Goods,candProdEmbed])

#WeightedGoods = tf.convert_to_tensor(WeightedGoods)
#print(Goods.shape)
#print(WeightedGoods.shape)
SeqPoolLayer = tf.reduce_sum(WeightedGoods,axis=1,keep_dims=True, name='pooling') #First Parameter was "Goods"
print(SeqPoolLayer.shape)
#SeqPoolLayer = tf.keras.backend.sum(Goods, axis=1, keepdims=True)

#Candidate = Concatenate()([candProdEmbed,candCateEmbed]) #Uncomment for original work
Candidate = candProdEmbed

#Candidate = tf.reshape(Candidate, (tf.shape(Candidate)[0],1, tf.shape(Candidate)[1]*tf.shape(Candidate)[2])) 
#Candidate = tf.reshape(Candidate,(Candidate.shape[0],1,Candidate.shape[1]*Candidate.shape[2]))

Concatendated = Concatenate()([ userEmbed, SeqPoolLayer, Candidate])
#print(Concatendated.shape)

#Flattened     = Lambda(lambda x: tf.keras.backend.batch_flatten(x))(Concatendated)
Flattened = Flatten()(Concatendated)
#print(Flattened.shape)

#BN = BatchNormalization()(Flattened)
#tf.convert_to_tensor(Flattened)

Dense1 =Dense(200) (Flattened)
Dense1 =Dropout(0.5) (Dense1)
PDense1 = PReLU() (Dense1)

#, kernel_initializer=TruncatedNormal() 1486

Dense2 = Dense(80)(PDense1)
Dense2 =Dropout(0.5) (Dense2)
PDense2 = PReLU() (Dense2)


CTR = Dense(2, activation='softmax', use_bias = False, name= 'ctr') (PDense2)

model = Model(inputs=[userInput, prodInput, candProdInput], outputs= [CTR])
#opt = tf.keras.optimizers.Adam(learning_rate=0.0001)
model.compile(optimizer= 'adam',
              loss='binary_crossentropy',
              metrics=['binary_accuracy'])

checkpointer = ModelCheckpoint(filepath = modelName+'.weights.best.hdf5', verbose=1, save_best_only = True)
#model.fit(X_train,y_train,epochs = 20, batch_size = 8)

model.fit([userId_train, prodId_train, candProd_train], [candRate], epochs = 1 ,callbacks=[checkpointer], shuffle= True, validation_split=0.2, batch_size = 200)


model.save(modelName+'.h5')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Hola
Instructions for updating:
keep_dims is deprecated, use keepdims instead
(?, 1, 400)
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 109320 samples, validate on 27331 samples
109200/109320 [============================>.] - ETA: 0s - loss: 0.5074 - binary_accuracy: 0.8102
Epoch 00001: val_loss improved from inf to 0.53707, saving model to digitalmusicalDrpbb.weights.best.hdf5
109320/109320 [==============================] - 34s 313us/sample - loss: 0.5073 - binary_accuracy: 0.8102 - val_loss: 0.5371 - val_binary_accuracy: 0.7926


In [ ]:
model.load_weights(modelName+'.weights.best.hdf5')

model.fit([userId_train, prodId_train, candProd_train], [candRate], epochs = 1 ,callbacks=[checkpointer], shuffle= True, validation_split=0.2, batch_size = 80)



Train on 109320 samples, validate on 27331 samples
109200/109320 [============================>.] - ETA: 0s - loss: 0.3083 - binary_accuracy: 0.8710
Epoch 00001: val_loss did not improve from 0.53707
109320/109320 [==============================] - 42s 389us/sample - loss: 0.3084 - binary_accuracy: 0.8709 - val_loss: 0.5870 - val_binary_accuracy: 0.7327


In [ ]:
model.load_weights(modelName+'.weights.best.hdf5')
model.evaluate([userId_test, prodId_test, candProd_test], [candRate_test])

16564/16564 [==============================] - 1s 87us/sample - loss: 0.4283 - binary_accuracy: 0.8301


[0.42826129551873465, 0.8301135]

In [ ]:
print(userId_test.shape)

(16564,)


In [ ]:
def saveData(modelName):
    mod = '/content/'+modelName+'.h5'
    wts = '/content/'+modelName+'.weights.best.hdf5'
    !cp $mod /content/drive/My\ Drive/ModelsAndWeights/Models/
    !cp $wts /content/drive/My\ Drive/ModelsAndWeights/Weights/
    # np.save('X_train_'+modelName+'.npy', X_train)
    # np.save('X_test_'+modelName+'.npy', X_test)
    # np.save('y_train_'+modelName+'.npy', y_train)
    # np.save('y_test_'+modelName+'.npy', y_test)
    # xtr = '/content/X_train_'+modelName+'.npy'
    # xts = '/content/X_test_'+modelName+'.npy'
    # ytr = '/content/y_train_'+modelName+'.npy'
    # yts = '/content/y_test_'+modelName+'.npy'

    # !cp $xtr /content/drive/My\ Drive/ModelData/
    # !cp $xts /content/drive/My\ Drive/ModelData/
    # !cp $ytr /content/drive/My\ Drive/ModelData/
    # !cp $yts /content/drive/My\ Drive/ModelData/


In [ ]:
saveData(
    modelName
)

In [ ]:
#modelName = 'RS4_build2' #Change Model Name !! IMPORTANT
model.load_weights(modelName+'.weights.best.hdf5')

# userId_test = vNormalize(userId_test,numUsers)
# prodId_test = vcNormalize(userId_test,numProds)
# candProd_test = vNormalize(userId_test,numProds)

p = model.predict( [userId_test, prodId_test,candProd_test])


count_ones=0
count_zeroes=0
for i in p:
    print(i)
    if i[0]<=i[1]:
        count_zeroes+=1
    else:
        count_ones+=1
print(count_ones)
print(count_zeroes)

Streaming output truncated to the last 5000 lines.
[0.94821835 0.05178165]
[0.8674392  0.13256083]
[0.9187265  0.08127347]
[0.9447262  0.05527369]
[0.89407057 0.1059294 ]
[0.9439914  0.05600854]
[0.5246205  0.47537956]
[0.9402961  0.05970391]
[0.80488    0.19511996]
[0.907368   0.09263203]
[0.96473885 0.03526109]
[0.95596933 0.04403063]
[0.89415747 0.10584252]
[0.92921436 0.07078561]
[0.9517153  0.04828471]
[0.43976468 0.5602353 ]
[0.9826737  0.01732626]
[0.98231053 0.01768943]
[0.95617133 0.04382866]
[0.94282347 0.05717652]
[0.63659227 0.36340776]
[0.94373184 0.05626811]
[0.71579856 0.2842014 ]
[0.9514218 0.0485782]
[0.9317574  0.06824256]
[0.9537065  0.04629353]
[0.38984203 0.61015797]
[0.888722   0.11127798]
[0.95758134 0.04241868]
[0.87566525 0.12433472]
[0.97584605 0.02415393]
[0.46188608 0.5381139 ]
[0.96377665 0.03622337]
[0.5018427  0.49815735]
[0.70537883 0.29462114]
[0.8297631  0.17023687]
[0.42810607 0.57189393]
[0.88683605 0.11316394]
[0.94881314 0.05118684]
[0.9436319  0.0

In [ ]:
print(userId_test[0])

1


In [ ]:
for i in p:
    print(i)

Streaming output truncated to the last 5000 lines.
[0.9418333  0.05816672]
[0.4775171 0.5224829]
[0.94821835 0.05178165]
[0.8674392  0.13256083]
[0.9187265  0.08127347]
[0.9447262  0.05527369]
[0.89407057 0.1059294 ]
[0.9439914  0.05600854]
[0.5246205  0.47537956]
[0.9402961  0.05970391]
[0.80488    0.19511996]
[0.907368   0.09263203]
[0.96473885 0.03526109]
[0.95596933 0.04403063]
[0.89415747 0.10584252]
[0.92921436 0.07078561]
[0.9517153  0.04828471]
[0.43976468 0.5602353 ]
[0.9826737  0.01732626]
[0.98231053 0.01768943]
[0.95617133 0.04382866]
[0.94282347 0.05717652]
[0.63659227 0.36340776]
[0.94373184 0.05626811]
[0.71579856 0.2842014 ]
[0.9514218 0.0485782]
[0.9317574  0.06824256]
[0.9537065  0.04629353]
[0.38984203 0.61015797]
[0.888722   0.11127798]
[0.95758134 0.04241868]
[0.87566525 0.12433472]
[0.97584605 0.02415393]
[0.46188608 0.5381139 ]
[0.96377665 0.03622337]
[0.5018427  0.49815735]
[0.70537883 0.29462114]
[0.8297631  0.17023687]
[0.42810607 0.57189393]
[0.88683605 0.113

In [ ]:
print(len(candProd_train))
print(len(p[:,0]))
def sort_list(list1, list2): 
  zipped_pairs = zip(list2, list1) 
  candprod = [ int(x) for _,x in sorted(zipped_pairs)] 
  predicts = sorted(list2,reverse=True)
  return candprod,predicts  
candprods,predicts = sort_list(candProd_train,p[:,0])
candprods = reversed(candprods)
#print(candprods[0])
print(predicts)

136651
16564
[0.99999785, 0.99985814, 0.9994881, 0.9990338, 0.9989114, 0.99872357, 0.99853826, 0.9985347, 0.99851424, 0.99775714, 0.9976859, 0.9976132, 0.99750143, 0.9973942, 0.9973236, 0.9972807, 0.9970306, 0.996977, 0.9966084, 0.9965474, 0.9964708, 0.9963961, 0.99628544, 0.9962231, 0.9962166, 0.99613935, 0.996101, 0.9957308, 0.99560153, 0.9955498, 0.9955172, 0.9954277, 0.9954007, 0.99536973, 0.99533635, 0.9951807, 0.9951396, 0.99506, 0.9949944, 0.9947541, 0.9947096, 0.99470407, 0.994643, 0.9944449, 0.99436486, 0.9943131, 0.9942783, 0.9942773, 0.99425006, 0.9942107, 0.99404234, 0.99400914, 0.9939943, 0.9939422, 0.9939143, 0.9938792, 0.9938573, 0.9938485, 0.99377465, 0.9935454, 0.9934589, 0.9932799, 0.993204, 0.9929745, 0.99295723, 0.9929502, 0.99294245, 0.9927619, 0.99247134, 0.99241745, 0.99240005, 0.99237835, 0.9923321, 0.9922754, 0.9922317, 0.9922259, 0.9922083, 0.99219996, 0.99213177, 0.9920237, 0.9920095, 0.99189794, 0.99189055, 0.99184567, 0.9917748, 0.9917555, 0.9915451, 0.9915

In [ ]:

print (userId_train.shape)
print(type(userId_train))
print (prodId_train.shape)
print(type(prodId_train))
print(candProd_train.shape)
print(type(candProd_train))

(136651, 1)
<class 'numpy.ndarray'>
(136651, 790)
<class 'numpy.ndarray'>
(136651, 1)
<class 'numpy.ndarray'>


In [ ]:
oo = 0
zz = 0
for i in candRate_test:
    if i[0] > i[1]:
        oo = oo+1
    else:
        zz = zz+1

print(oo)
print(zz)

13318
3246


In [ ]:
print(oo/(oo+zz))

0.8040328423086212


In [ ]:
for i in candRate_test:
    print(i)

Streaming output truncated to the last 5000 lines.
[1 0]
[1 0]
[1 0]
[0 1]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[0 1]
[1 0]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[0 1]
[0 1]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[1 0]
[1 0]
[0 1]
[1 0]
[1 0]
[0 1]
[1 0]
[0 1]
[1 0]
[

In [ ]:
cnt = 0
c= 0
for i in range(0,len(candRate_test)):
    if candRate_test[i][0] < 0.5:
        c+= 1
        if p[i][0] < 0.5:
            cnt+= 1

print(cnt)
print(c)


1014
3246


In [ ]:
model.load_weights(modelName+'.weights.best.hdf5')


Base Model (Run this cell and skip running DIN for BM)


In [ ]:
from tensorflow.python.keras.models import Model
import numpy as np
from tensorflow.python.keras.models import Sequential, load_model
from tensorflow.python.keras.layers import  AveragePooling1D, Flatten, Dense, Dropout, Embedding, Lambda, Input, Concatenate, PReLU, BatchNormalization
from tensorflow.python.keras.callbacks import ModelCheckpoint
from tensorflow.python.keras.metrics import binary_accuracy , categorical_accuracy
from tensorflow.python.keras import regularizers
from tensorflow.python.keras.initializers import TruncatedNormal
import tensorflow as tf

embedOutDim = 400 #200,400,1000
attention_scale = 100 #1,10,100
poolSize = 2

#, embeddings_regularizer= regularizers.l2(0.01) 1485

##################################################################
userInput =  Input(shape=(1,), name= 'users')
#userInput =  tf.keras.layers.Masking(mask_value=0.0)(userInput)
userEmbed =  Embedding(input_dim =numberOfUsers+1,output_dim= embedOutDim, mask_zero =True) (userInput)


##################################################################
prodInput =  Input(shape=(maxLen,), name= 'products') #batch_shape(None, None)
#prodInputs =  tf.keras.layers.Masking(mask_value=0)(prodInput)
prodEmbed =  Embedding(input_dim =numProds,output_dim= embedOutDim, mask_zero =True ) (prodInput)
#print(prodInput.shape)

##################################################################
# cateInput = Input(shape=(11,), name= 'categories')
# cateEmbed =  Embedding(input_dim = numberOfCategories , output_dim=embedOutDim, embeddings_regularizer= regularizers.l2(0.01)) (cateInput)

##################################################################
candProdInput = Input(shape=(1,),  name= 'candidateProdId')
candProdEmbed =  Embedding(input_dim = numProds +1 , output_dim=embedOutDim, mask_zero =True) (candProdInput)

##################################################################
# candCateInput = Input(shape=(1,),  name= 'candidateCateId')
# candCateEmbed =  Embedding(input_dim = numberOfCategories , output_dim=embedOutDim, embeddings_regularizer= regularizers.l2(0.01)) (candCateInput)

#lenInput = Input(shape=(1,), name= 'len_of_products')

candProdEmbed = Dropout(0.5)(candProdEmbed)
prodEmbed = Dropout(0.5)(prodEmbed)
userEmbed = Dropout(0.5)(userEmbed)


#Goods  =Concatenate()([prodEmbed,cateEmbed]) #Uncomment for original work 
Goods = prodEmbed

#Goods  =  Lambda(lambda x: tf.keras.backend.batch_flatten(x))(Goods)
#print(Goods.shape)
# SeqPoolLayer = SequencePoolingLayer("sum",supports_masking= False)([Goods,lenInput]) #Error 

SeqPoolLayer = tf.reduce_sum(Goods,axis=1,keep_dims=True, name='pooling') #First Parameter was "Goods"

#SeqPoolLayer = tf.keras.backend.sum(Goods, axis=1, keepdims=True)

#Candidate = Concatenate()([candProdEmbed,candCateEmbed]) #Uncomment for original work
Candidate = candProdEmbed

#Candidate = tf.reshape(Candidate, (tf.shape(Candidate)[0],1, tf.shape(Candidate)[1]*tf.shape(Candidate)[2])) 
#Candidate = tf.reshape(Candidate,(Candidate.shape[0],1,Candidate.shape[1]*Candidate.shape[2]))

Concatendated = Concatenate()([ userEmbed, SeqPoolLayer, Candidate])
#print(Concatendated.shape)

#Flattened     = Lambda(lambda x: tf.keras.backend.batch_flatten(x))(Concatendated)
Flattened = Flatten()(Concatendated)
#print(Flattened.shape)

#BN = BatchNormalization()(Flattened)
#tf.convert_to_tensor(Flattened)

Dense1 =Dense(200) (Flattened)
Dense1 =Dropout(0.5) (Dense1)
PDense1 = PReLU() (Dense1)

#, kernel_initializer=TruncatedNormal() 1486

Dense2 = Dense(80)(PDense1)
Dense2 =Dropout(0.5) (Dense2)
PDense2 = PReLU() (Dense2)


CTR = Dense(2, activation='softmax', use_bias = False, name= 'ctr') (PDense2)

model = Model(inputs=[userInput, prodInput, candProdInput], outputs= [CTR])
#opt = tf.keras.optimizers.Adam(learning_rate=0.0001)
model.compile(optimizer= 'adam',
              loss='binary_crossentropy',
              metrics=['binary_accuracy'])

checkpointer = ModelCheckpoint(filepath = modelName+'.weights.best.hdf5', verbose=1, save_best_only = True)
#model.fit(X_train,y_train,epochs = 20, batch_size = 8)

model.fit([userId_train, prodId_train, candProd_train], [candRate], epochs = 1 ,callbacks=[checkpointer], shuffle= True, validation_split=0.2, batch_size = 200)


model.save(modelName+'.h5')